export type NicheStatus = "check" | "test" | "seasonal" | "restricted";

export type Niche = {
  rank: number;
  sourceName: string;
  name: string;
  revenue: number;
  growth: number;
  orders: number;
  averageCheck: number;
  activeSku: number;
  sellers: number;
  unbrandedShare: number;
  medianReviews: number;
  lowReviewRevenueShare: number;
  status: NicheStatus;
  season: string;
  verdict: string;
};

export const niches: Niche[] = [
  {
    rank: 1,
    sourceName: "Двигатель в сборе",
    name: "Двигатели в сборе",
    revenue: 65.3,
    growth: -39,
    orders: 146,
    averageCheck: 447,
    activeSku: 32,
    sellers: 28,
    unbrandedShare: 43.1,
    medianReviews: 6,
    lowReviewRevenueShare: 46.2,
    status: "test",
    season: "Сезонность не главный риск",
    verdict: "Я бы рассматривал эту нишу только с экспертом по автокомпонентам: ошибка в совместимости превращается в очень дорогой возврат.",
  },
  {
    rank: 2,
    sourceName: "Багажные боксы",
    name: "Багажные боксы",
    revenue: 120,
    growth: 58.6,
    orders: 1069,
    averageCheck: 112.2,
    activeSku: 143,
    sellers: 56,
    unbrandedShare: 41.5,
    medianReviews: 7,
    lowReviewRevenueShare: 34.7,
    status: "seasonal",
    season: "Август→сентябрь: −49,7%",
    verdict: "Рост относится к летнему сезону. Я бы вернулся к этой нише заранее перед следующим сезоном, а не наращивал остатки к осени.",
  },
  {
    rank: 3,
    sourceName: "Садовые качели",
    name: "Садовые качели",
    revenue: 157.4,
    growth: 4.3,
    orders: 1298,
    averageCheck: 121.3,
    activeSku: 74,
    sellers: 56,
    unbrandedShare: 30,
    medianReviews: 10,
    lowReviewRevenueShare: 11.2,
    status: "seasonal",
    season: "Август→сентябрь: −66,7%",
    verdict: "В июне эта категория находится на пике. Сейчас я бы не делал большой заказ, даже при высокой месячной выручке.",
  },
  {
    rank: 4,
    sourceName: "Виброплатформы",
    name: "Виброплатформы",
    revenue: 62.3,
    growth: -39.4,
    orders: 2011,
    averageCheck: 31,
    activeSku: 95,
    sellers: 69,
    unbrandedShare: 27.9,
    medianReviews: 31,
    lowReviewRevenueShare: 5.5,
    status: "test",
    season: "Сначала проверить причину снижения",
    verdict: "Я бы тестировал только новинку, полезную функцию, лучшую комплектацию или сервис. Начал бы с небольшой партии.",
  },
  {
    rank: 5,
    sourceName: "Комплекты садовой мебели",
    name: "Комплекты садовой мебели",
    revenue: 321.1,
    growth: 59,
    orders: 1360,
    averageCheck: 236.1,
    activeSku: 236,
    sellers: 68,
    unbrandedShare: 26.4,
    medianReviews: 2,
    lowReviewRevenueShare: 43.9,
    status: "seasonal",
    season: "Август→сентябрь: −42,2%",
    verdict: "Новые карточки здесь продают, но сезон заканчивается. Сейчас важнее не заморозить деньги в остатках.",
  },
  {
    rank: 6,
    sourceName: "Ванны",
    name: "Ванны",
    revenue: 68.8,
    growth: 26,
    orders: 683,
    averageCheck: 100.7,
    activeSku: 186,
    sellers: 51,
    unbrandedShare: 26.4,
    medianReviews: 6,
    lowReviewRevenueShare: 53.1,
    status: "test",
    season: "Спрос выглядит умеренно ровным",
    verdict: "Рынок относительно открыт для новых карточек, но до закупки я бы посчитал бой, возвраты, подъём и крупногабаритную доставку.",
  },
  {
    rank: 7,
    sourceName: "Льдогенераторы",
    name: "Льдогенераторы",
    revenue: 68.7,
    growth: 13.6,
    orders: 800,
    averageCheck: 85.9,
    activeSku: 48,
    sellers: 61,
    unbrandedShare: 20.8,
    medianReviews: 8,
    lowReviewRevenueShare: 29.3,
    status: "seasonal",
    season: "Август→сентябрь: −32,2%",
    verdict: "Летний товар. Я бы рассматривал только короткий тест без большого остатка на осень.",
  },
  {
    rank: 8,
    sourceName: "Скутеры и мопеды",
    name: "Скутеры и мопеды",
    revenue: 165.3,
    growth: 20.1,
    orders: 408,
    averageCheck: 405.2,
    activeSku: 52,
    sellers: 15,
    unbrandedShare: 20.6,
    medianReviews: 20,
    lowReviewRevenueShare: 15.2,
    status: "seasonal",
    season: "Сентябрь→октябрь: −42,5%",
    verdict: "Высокий чек, гарантия и сервис усиливают риск осеннего остатка. Я бы отложил запуск до подготовки к новому сезону.",
  },
  {
    rank: 9,
    sourceName: "Барбекю, грили и коптильни",
    name: "Барбекю, грили и коптильни",
    revenue: 81.1,
    growth: 0.6,
    orders: 815,
    averageCheck: 99.5,
    activeSku: 99,
    sellers: 73,
    unbrandedShare: 20.3,
    medianReviews: 7,
    lowReviewRevenueShare: 27,
    status: "seasonal",
    season: "Август→сентябрь: −44,8%",
    verdict: "Я бы готовил ассортимент заранее к следующему лету, но не закупал большую партию сейчас.",
  },
  {
    rank: 10,
    sourceName: "Каркасные батуты",
    name: "Каркасные батуты",
    revenue: 96.1,
    growth: 42.5,
    orders: 1622,
    averageCheck: 59.2,
    activeSku: 86,
    sellers: 81,
    unbrandedShare: 13.4,
    medianReviews: 7,
    lowReviewRevenueShare: 20.6,
    status: "seasonal",
    season: "Август→сентябрь: −30,1%",
    verdict: "Июньский рост сезонный. Осенний запуск может оставить товар на складе до весны.",
  },
  {
    rank: 11,
    sourceName: "Силовые тренажеры",
    name: "Силовые тренажёры",
    revenue: 105.9,
    growth: 9.8,
    orders: 618,
    averageCheck: 171.3,
    activeSku: 77,
    sellers: 64,
    unbrandedShare: 11.2,
    medianReviews: 8,
    lowReviewRevenueShare: 34.3,
    status: "check",
    season: "Сентябрь→октябрь: +52,0%",
    verdict: "Один из сильных осенних кандидатов. Я бы проверил компактные домашние модели, сборку, расходники и гарантийный сервис.",
  },
  {
    rank: 12,
    sourceName: "Тестомесы",
    name: "Тестомесы",
    revenue: 110,
    growth: -24.4,
    orders: 1869,
    averageCheck: 58.8,
    activeSku: 100,
    sellers: 85,
    unbrandedShare: 10.5,
    medianReviews: 24,
    lowReviewRevenueShare: 13.8,
    status: "test",
    season: "Август→сентябрь: +16,9%",
    verdict: "Осенний сигнал хороший, но рынок сейчас снижается. Я бы дождался подтверждения разворота и только потом тестировал небольшую партию.",
  },
  {
    rank: 13,
    sourceName: "Садовые шатры",
    name: "Садовые шатры",
    revenue: 69.7,
    growth: 124.3,
    orders: 822,
    averageCheck: 84.8,
    activeSku: 53,
    sellers: 41,
    unbrandedShare: 9.9,
    medianReviews: 9,
    lowReviewRevenueShare: 22.2,
    status: "seasonal",
    season: "После сентября: до −86,1%",
    verdict: "Рост отражает пик сезона. Для нового запуска сейчас уже поздно.",
  },
  {
    rank: 14,
    sourceName: "Портативные зарядные устройства для кемпинга",
    name: "Портативные зарядные станции",
    revenue: 92.3,
    growth: 42.3,
    orders: 409,
    averageCheck: 225.8,
    activeSku: 68,
    sellers: 52,
    unbrandedShare: 9.2,
    medianReviews: 4,
    lowReviewRevenueShare: 36.8,
    status: "test",
    season: "Кемпинг ослабевает к осени",
    verdict: "Я бы проверял сценарий аварийного питания дома, а не делал ставку только на кемпинг. Критичны батарея, гарантия и честные характеристики.",
  },
  {
    rank: 15,
    sourceName: "Тенты и купола для бассейнов",
    name: "Тенты и купола для бассейнов",
    revenue: 96.5,
    growth: 728.9,
    orders: 13813,
    averageCheck: 7,
    activeSku: 91,
    sellers: 96,
    unbrandedShare: 8.7,
    medianReviews: 15,
    lowReviewRevenueShare: 12.3,
    status: "seasonal",
    season: "Август→сентябрь: −86,8%",
    verdict: "Рост в семь раз показывает летний пик, а не новый постоянный тренд. К осени я бы не входил.",
  },
  {
    rank: 16,
    sourceName: "Кулеры для воды",
    name: "Кулеры для воды",
    revenue: 51.3,
    growth: 19.1,
    orders: 1743,
    averageCheck: 29.4,
    activeSku: 108,
    sellers: 74,
    unbrandedShare: 8.5,
    medianReviews: 19,
    lowReviewRevenueShare: 19,
    status: "check",
    season: "Спрос ровнее сезонных ниш",
    verdict: "Один из самых понятных вариантов для ограниченного теста. Я бы отдельно проверил протечки, упаковку и доступность сервиса.",
  },
  {
    rank: 17,
    sourceName: "Доильные аппараты",
    name: "Доильные аппараты",
    revenue: 66.6,
    growth: -14.4,
    orders: 390,
    averageCheck: 170.8,
    activeSku: 44,
    sellers: 30,
    unbrandedShare: 7.7,
    medianReviews: 13,
    lowReviewRevenueShare: 17.1,
    status: "test",
    season: "Специализированный спрос",
    verdict: "Небольшое число продавцов выглядит интересно, но без отраслевой экспертизы, расходников и ремонта я бы не заходил.",
  },
  {
    rank: 18,
    sourceName: "Межкомнатные двери",
    name: "Межкомнатные двери",
    revenue: 61.6,
    growth: 38.9,
    orders: 1628,
    averageCheck: 37.8,
    activeSku: 266,
    sellers: 50,
    unbrandedShare: 7.6,
    medianReviews: 5,
    lowReviewRevenueShare: 46.4,
    status: "test",
    season: "Текущий спрос растёт",
    verdict: "Вход по отзывам открыт, но решает операция: замер, сторона открывания, оттенок, комплектность, упаковка и доставка.",
  },
  {
    rank: 19,
    sourceName: "Электросамокаты",
    name: "Электросамокаты",
    revenue: 199,
    growth: -4.3,
    orders: 1007,
    averageCheck: 197.6,
    activeSku: 117,
    sellers: 66,
    unbrandedShare: 7,
    medianReviews: 9,
    lowReviewRevenueShare: 29.5,
    status: "seasonal",
    season: "Август→сентябрь: −55,0%",
    verdict: "Сезон уже разворачивается вниз, а батарея, гарантия и запчасти добавляют риски. Я бы отложил.",
  },
  {
    rank: 20,
    sourceName: "Мотоциклы",
    name: "Мотоциклы",
    revenue: 195.4,
    growth: -52.5,
    orders: 293,
    averageCheck: 667,
    activeSku: 99,
    sellers: 34,
    unbrandedShare: 6.2,
    medianReviews: 5,
    lowReviewRevenueShare: 59.1,
    status: "seasonal",
    season: "Август→сентябрь: −38,0%",
    verdict: "Падение, высокий капитал и обязательный сервис делают осенний вход нерациональным для новичка.",
  },
  {
    rank: 21,
    sourceName: "Велотренажеры",
    name: "Велотренажёры",
    revenue: 98.2,
    growth: 15.5,
    orders: 1779,
    averageCheck: 55.2,
    activeSku: 130,
    sellers: 98,
    unbrandedShare: 6,
    medianReviews: 27,
    lowReviewRevenueShare: 24.6,
    status: "check",
    season: "Сентябрь→октябрь: +21,3%",
    verdict: "Рынок есть, но новая карточка должна отличаться продуктом, контентом или сервисом. Я бы проверил компактность, шум и устойчивость.",
  },
  {
    rank: 22,
    sourceName: "Смарт-очки",
    name: "Смарт-очки",
    revenue: 201.4,
    growth: 33.6,
    orders: 1748,
    averageCheck: 115.2,
    activeSku: 111,
    sellers: 100,
    unbrandedShare: 5.7,
    medianReviews: 7,
    lowReviewRevenueShare: 21.2,
    status: "check",
    season: "Август→сентябрь: +36,3%",
    verdict: "Интересный рынок, но не для безымянной копии. Я бы проверял происхождение товара, приложение, совместимость и гарантию.",
  },
  {
    rank: 23,
    sourceName: "Здоровье глаз",
    name: "Здоровье глаз",
    revenue: 64.5,
    growth: 0.9,
    orders: 12998,
    averageCheck: 5,
    activeSku: 138,
    sellers: 20,
    unbrandedShare: 5.5,
    medianReviews: 33,
    lowReviewRevenueShare: 3.8,
    status: "restricted",
    season: "Спрос не равен разрешению на продажу",
    verdict: "Я не считаю это обычной товарной нишей: сначала нужна правовая проверка конкретного товара, документов, хранения и рекламы.",
  },
  {
    rank: 24,
    sourceName: "Комплекты для гостиной",
    name: "Комплекты для гостиной",
    revenue: 118.1,
    growth: 32.2,
    orders: 347,
    averageCheck: 340.3,
    activeSku: 98,
    sellers: 72,
    unbrandedShare: 5.1,
    medianReviews: 9,
    lowReviewRevenueShare: 19.9,
    status: "check",
    season: "Сентябрь→октябрь: +15,8%",
    verdict: "Сильный кандидат для продавца с крупногабаритной логистикой. Я бы начал с одного-двух комплектов и очень точной карточки.",
  },
  {
    rank: 25,
    sourceName: "Гладильные доски",
    name: "Гладильные доски",
    revenue: 71,
    growth: 9,
    orders: 3980,
    averageCheck: 17.8,
    activeSku: 198,
    sellers: 97,
    unbrandedShare: 5.1,
    medianReviews: 30,
    lowReviewRevenueShare: 8.2,
    status: "restricted",
    season: "Сезонность не решает проблему маржи",
    verdict: "Сильные карточки уже забирают рынок, а крупная доставка при низком чеке может съесть прибыль. Нужна исключительная закупочная цена.",
  },
  {
    rank: 26,
    sourceName: "Холодильные витрины",
    name: "Холодильные витрины",
    revenue: 173.9,
    growth: -16.3,
    orders: 624,
    averageCheck: 278.7,
    activeSku: 92,
    sellers: 57,
    unbrandedShare: 5,
    medianReviews: 8,
    lowReviewRevenueShare: 33.2,
    status: "test",
    season: "Сначала подтвердить восстановление спроса",
    verdict: "Это дорогая профессиональная покупка. Я бы заходил только с монтажом, гарантией, запчастями и понятной B2B-продажей.",
  },
  {
    rank: 27,
    sourceName: "Лодочные моторы",
    name: "Лодочные моторы",
    revenue: 203.1,
    growth: 46.6,
    orders: 608,
    averageCheck: 334,
    activeSku: 83,
    sellers: 46,
    unbrandedShare: 4.1,
    medianReviews: 14,
    lowReviewRevenueShare: 18.8,
    status: "seasonal",
    season: "Август→сентябрь: −46,0%",
    verdict: "В июне рынок находится на пике. Я бы перенёс закупку на подготовку к следующему сезону и заранее продумал гарантию и сервис.",
  },
  {
    rank: 28,
    sourceName: "Мышцы, кости и суставы",
    name: "Мышцы, кости и суставы",
    revenue: 56.5,
    growth: -0.1,
    orders: 6450,
    averageCheck: 8.8,
    activeSku: 97,
    sellers: 15,
    unbrandedShare: 3.7,
    medianReviews: 32,
    lowReviewRevenueShare: 15.7,
    status: "restricted",
    season: "Спрос выглядит ровным",
    verdict: "Для части товаров могут требоваться специальные документы. Я бы принимал решение только после проверки конкретного ассортимента.",
  },
  {
    rank: 29,
    sourceName: "Воздухоохладители",
    name: "Воздухоохладители",
    revenue: 124.4,
    growth: 417.4,
    orders: 2325,
    averageCheck: 53.5,
    activeSku: 33,
    sellers: 47,
    unbrandedShare: 3.5,
    medianReviews: 27,
    lowReviewRevenueShare: 7.4,
    status: "seasonal",
    season: "Полной истории пока недостаточно",
    verdict: "Я бы не закупал товар по одному месяцу яркого роста. Сначала нужен ещё один полный период и разбор причин низких оценок.",
  },
  {
    rank: 30,
    sourceName: "Беговые дорожки",
    name: "Беговые дорожки",
    revenue: 414.8,
    growth: 8.3,
    orders: 2974,
    averageCheck: 139.5,
    activeSku: 171,
    sellers: 67,
    unbrandedShare: 3.5,
    medianReviews: 31,
    lowReviewRevenueShare: 10.9,
    status: "check",
    season: "Сентябрь→октябрь: +25,3%",
    verdict: "Самый большой рынок в выборке. Я бы тестировал небольшую линейку складных моделей с понятной сборкой, доставкой и запасными частями.",
  },
];

export const statusOrder: NicheStatus[] = ["check", "test", "seasonal", "restricted"];

export const statusCopy: Record<NicheStatus, { label: string; title: string; description: string }> = {
  check: {
    label: "Проверить сейчас",
    title: "Кандидаты для осенней проверки",
    description: "Здесь я вижу сочетание спроса и хорошего сезонного сигнала. Но это ещё не закупочный лист. Сначала я бы проверил конкретные товары внутри каждой категории.",
  },
  test: {
    label: "Только тест",
    title: "Небольшой тест после дополнительной проверки",
    description: "В этих нишах я вижу возможность, но риски уже заметны. Я бы начинал с ограниченной партии и заранее решил, при каких результатах остановить тест.",
  },
  seasonal: {
    label: "Не к осени",
    title: "Вернуться перед следующим сезоном",
    description: "Высокие июньские цифры здесь я объясняю летним сезоном. Хорошая выручка в пик ещё не означает, что в сентябре получится удачно зайти в категорию.",
  },
  restricted: {
    label: "Не для первого запуска",
    title: "Не рассматривать как обычный первый товар",
    description: "Эти ниши я не рассматриваю как простой первый запуск. Здесь есть специальные требования к товару или слишком высокий барьер карточек и логистики.",
  },
};

export const firstPriorityNames = [
  "Беговые дорожки",
  "Силовые тренажёры",
  "Комплекты для гостиной",
  "Кулеры для воды",
  "Велотренажёры",
];
